[versions]
agp = "8.13.2"
dokka = "2.1.0"
kotlin = "2.3.0"
kotlinBinaryCompatibility = "0.18.1"
jvmTarget = "17"
nexusPlugin = "0.35.0"
androidxMaterial = "1.13.0"
androidxAppcompat = "1.7.1"
androidxMacroBenchmark = "1.4.1"
androidxTest = "1.7.0"
baselineProfiles = "1.4.1"
uiAutomator = "2.3.0"
spotless = "8.1.0"
powerMenu = "2.2.4"
timber = "5.0.1"
junit = "1.3.0"
espresso-core = "3.7.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nexus-plugin = { id = "com.vanniktech.maven.publish", version.ref = "nexusPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
baseline-profile = { id = "androidx.baselineprofile", version.ref = "androidxMacroBenchmark" }
kotlin-binary-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibility" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
androidx-material = { module = "com.google.android.material:material", version.ref = "androidxMaterial" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
powermenu = { module = "com.github.skydoves:powermenu", version.ref = "powerMenu" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# unit test
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTest" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "baselineProfiles" }
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
